name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of game to build e.g. "1.0.0"'     
        required: true
        type: string

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: LonaRPG-MTL
  PROJECT_PATH: project
  ITCH_GAME: lonarpg-mtl
  ITCH_USER: tetragramat

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Prepare build addons
        run: cp build/README.txt build/windows/README.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: windows
          path: build/windows
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          PACKAGE: build/windows
          VERSION: ${{ inputs.version }}
