name: Test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of game to build e.g. "1.0.0"'     
        required: true
        type: string

env:
  GODOT_VERSION: 4.2.2
  EXPORT_NAME: LonaRPG-MTL
  PROJECT_PATH: project
  ITCH_GAME: lonarpg-mtl
  ITCH_USER: tetragramat

jobs:
  export-linux:
    name: Linux/X11 Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux/X11 Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Linux/X11" ../build/linux/$EXPORT_NAME.zip
      - name: Prepare build addons
        run: |
          cd build
          zip -u linux/$EXPORT_NAME.zip README.txt
          cd ..
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: linux
          path: build/linux/$EXPORT_NAME.zip
      - uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          PACKAGE: build/linux/$EXPORT_NAME.zip
          VERSION: ${{ inputs.version }}
      # - name: Release
      #   uses: softprops/action-gh-release@v2.0.2
      #   with:
      #     tag_name: ${{ github.event.inputs.version }}
